#!/usr/bin/env bash
usage() {
    echo "$0 [COMMAND]"
    echo ""
    echo "Hint: All commands expect a Python dev virtual environment to be active"
    echo ""
    echo "  Commands:"
    echo "  - lint                :    run ruff on all packages or on specific directories defining them as input, e.g., bash ./run lint hdhelpers"
    echo "  - test                :    run pytest on all packages or on specific directories defining them as input, e.g., bash ./run test test"
    echo "  - typecheck           :    run mypy static type check"
    echo "  - format              :    run ruff format"
    echo "  - check               :    run format check, tests, typechecking"
    echo "  - create_docu         :    runs sphinx to generate python pcakge documentation"
}

set -euo pipefail

fn_exists() {
    LC_ALL=C type "${1:-}" 2>/dev/null | grep -q 'function'
}
COMMAND="${1:-}"
shift
ARGUMENTS=("${@}")

#----- subcommands -----#


lint(){
    if (( ${#} == 0 )) ; then
        uv ruff check hdhelpers --exclude "**/__init__.py"
    else
        uv ruff check "${@}"
    fi
}

create_docu(){
    uv pip install .
    sphinx-build -M html docs/source docs/build
    sphinx-build -M doctest docs/source docs/build
    python -m pytest --doctest-modules src/hdhelpers/metadata/specs.py
}


format() {
    ruff check --select I src tests --fix "${@}" && echo "--> Ruff import sorting run."
    ruff format src tests "${@}" && echo "--> ruff format run."
}


test() {
    if (( ${#} == 0 )) ; then
        echo "Testing hdhelpers package code ..."
        python -m pytest tests -c pytest.ini \
        --cov=hdhelpers --no-cov-on-fail \
        --ignore=*/__init__.py
        coverage xml -i -o coverage.xml
    else
        python -m pytest "${@}" \
        --cov="${@}" \
        --no-cov-on-fail --cov-report=term-missing:skip-covered
    fi
}


typecheck() {
    python -m mypy "${@}" src
}


check() {
    # Will fail with non-zero exit status if any tool has some complaint.
    # If everything is okay this will have 0 exits status
    echo "--> Running ruff format in check mode" && ruff format src tests --check &&
        echo "--> Running tests" && python -m pytest tests -c pytest.ini --cov=. --cov-report=term-missing --cov-fail-under=80 &&
        echo "--> Running mypy" && python -m mypy src &&
        echo "--> Running ruff" && ruff check src tests &&
        echo "--> Creating docu" && install_editable_package && create_docu &&
        echo "CHECKS EXECUTION RESULTS: All checks were successful!"
}

install_editable_package(){
    pip install -e .
}

#----- Execution -----#
if fn_exists "$COMMAND"; then
    # cd into the script's current directory
    cd "${0%/*}" || exit 1
    # Execute
    TIMEFORMAT=$'\nTask completed in %3lR'
    time "$COMMAND" "${ARGUMENTS[@]}"
else
    usage
fi
